import Head from "next/head";
import styles from "@/styles/Features.module.scss";

import { DM_Sans } from "@next/font/google";
const dmSans = DM_Sans({ subsets: ["latin"], weight: ["400", "700"] });

import { Header, Layout, Tool, BetaSection, Footer } from "components";

import { tools } from "@/data/features_tools";

export default function Features() {
    const featuresTools = tools.map((tool, index) => (
        <Tool
            key={index}
            icon={tool.icon}
            header={tool.header}
            paragraph={tool.paragraph}
        />
    ));

    return (
        <div className={dmSans.className}>
            <Head>
                <title>
                    Frontend Mentor | Photosnap Website Challenge | Features
                </title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/assets/favicon-32x32.png" />
            </Head>

            <Header />

            <main className={styles.main}>
                <Layout
                    small="/assets/features/mobile/hero.jpg"
                    medium="/assets/features/tablet/hero.jpg"
                    large="/assets/features/desktop/hero.jpg"
                    header="features"
                    paragraph="We make sure all of our features are designed to be loved by every aspiring and even professional photograpers who wanted to share their stories."
                    theme="dark"
                    direction="reverse"
                    title=""
                />
            </main>

            <section aria-label="tools" className={styles.section_tools}>
                <div className={styles.tools_container}>{featuresTools}</div>
            </section>
            <BetaSection />
            <Footer />
        </div>
    );
}
