import Head from "next/head";
import styles from "@/styles/Pricing.module.scss";

import { DM_Sans } from "@next/font/google";
const dmSans = DM_Sans({ subsets: ["latin"], weight: ["400", "700"] });

import {
    Header,
    Layout,
    PriceCards,
    TablePlan,
    BetaSection,
    Footer
} from "components";

export default function Pricing() {
    return (
        <div className={dmSans.className}>
            <Head>
                <title>
                    Frontend Mentor | Photosnap Website Challenge | Pricing
                </title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/assets/favicon-32x32.png" />
            </Head>

            <Header />

            <main className={styles.main}>
                <Layout
                    small="/assets/pricing/mobile/hero.jpg"
                    medium="/assets/pricing/tablet/hero.jpg"
                    large="/assets/pricing/desktop/hero.jpg"
                    header="pricing"
                    paragraph="Create a your stories, Photosnap is a platform for photographers and visual storytellers. It’s the simple way to create and share your photos."
                    theme="dark"
                    direction="reverse"
                    title=""
                />

                <div className={styles.price_containter}>
                    <div className={styles.price_containter_wrap}>
                        <PriceCards />
                        <TablePlan />
                    </div>
                </div>
            </main>
            <BetaSection />
            <Footer />
        </div>
    );
}
