import Head from "next/head";
import styles from "@/styles/Stories.module.scss";

import { DM_Sans } from "@next/font/google";
const dmSans = DM_Sans({ subsets: ["latin"], weight: ["400", "700"] });

import { Header, GetInvite, StoryPicture, Footer } from "components";

import { stories } from "@/data/stories";

export default function Stories() {
    const desktop = 1180;
    const tablet = 720;
    const allStories = stories.map((story, index) => (
        <StoryPicture
            key={index}
            large={story.picture.desktop}
            small={story.picture.mobile}
            date={story.date}
            header={story.header}
            author={story.author}
        />
    ));

    return (
        <div className={dmSans.className}>
            <Head>
                <title>
                    Frontend Mentor | Photosnap Website Challenge | Stories
                </title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/assets/favicon-32x32.png" />
            </Head>

            <Header />

            <main className={styles.main}>
                <picture className={styles.main_img}>
                    <source
                        srcSet="assets/stories/desktop/moon-of-appalacia.jpg"
                        media={`(min-width:${desktop}px)`}
                    />
                    <source
                        srcSet="assets/stories/tablet/moon-of-appalacia.jpg"
                        media={`(min-width:${tablet}px)`}
                    />
                    <img
                        src="assets/stories/mobile/moon-of-appalacia.jpg"
                        alt=""
                    />
                </picture>
                <div className={styles.main_info}>
                    <div className={styles.info}>
                        <p className={styles.last_story}>
                            last month’s featured story
                        </p>
                        <h1>hazy full moon of appalachia </h1>
                        <p className={styles.info_details}>
                            March 2nd 2020 by John Appleseed
                        </p>
                        <p>
                            Create a your stories, Photosnap is a platform for
                            photographers and visual storytellers. It’s the
                            simple way to create and share your photos.
                        </p>
                        <GetInvite title="read the story" theme="dark" />
                    </div>
                </div>
            </main>

            <section aria-label="stories" className={styles.section_stories}>
                {allStories}
            </section>
            <Footer />
        </div>
    );
}
